########        Commentator Makefile      ########
#####                                        #####
#####      		Makefile written by 		 #####
#####				Joe Abdo	             #####
##################################################

EXEC = Commentator
CXXFLAGS = --std=c++17 -lstdc++fs -O0 -Wall
DEBUG = no
CC= g++-8

.PHONY: all clean debug-memory debuging

all: $(EXEC)

$(EXEC): main.o Directory.o Header.o Menu.o LinuxNotification.o Parse.o ParseCpp.o ParseJava.o Static.o #Indenter.o
	$(CC) -o $@ $^ $(CXXFLAGS)

main.o: main.cpp Directory.h  Menu.h Header.h Parse.h ParseCpp.h ParseJava.h Static.h #Indenter.h
	$(CC) $(CXXFLAGS) -o $@ -c $< 

Directory.o: Directory.cpp Directory.h Static.h
	$(CC) $(CXXFLAGS) -o $@ -c $<

Header.o: Header.cpp Header.h Static.h
	$(CC) $(CXXFLAGS) -o $@ -c $<

# Indenter.o: Indenter.cpp Indenter.h
# 	$(CC) $(CXXFLAGS) -o $@ -c $

LinuxNotification.o: LinuxNotification.cpp LinuxNotification.h Static.h
	$(CC) $(CXXFLAGS) -o $@ -c $<

Menu.o: Menu.cpp Menu.h Directory.h Header.h
	$(CC) $(CXXFLAGS) -o $@ -c $<

Parse.o: Parse.cpp Parse.h Header.h Static.h
	$(CC) $(CXXFLAGS) -o $@ -c $<

ParceCpp.o: ParceCpp.cpp ParceCpp.h Parce.h
	$(CC) $(CXXFLAGS) -o $@ -c $<

ParceJava.o: ParceJava.cpp ParceJava.h Parce.h
	$(CC) $(CXXFLAGS) -o $@ -c $<

Static.o: Static.cpp Static.h
	$(CC) $(CXXFLAGS) -o $@ -c $<

# Instruction to clean file generated by compilation
# 	as well as text files used
clean:
	rm *.o && rm $(EXEC)

# Instruction to clean the commented folder containing commented files
cleanCommented:
	rm -rf commented && rm -rf test/commented
	
# Instruction to check for memory leaks with valgrind
debug-memory: $(EXEC)
	valgrind --leak-check=full -v --show-leak-kinds=all\
	 --track-origins=yes ./$(EXEC)

# Instruction to compile and run at the same time
run: $(EXEC)
	./$(EXEC)
