########        Commentator Makefile      ########
#####                                        #####
#####      		Makefile written by 		 #####
#####				Joe Abdo	             #####
##################################################

EXEC = Commentator
CXXFLAGS = -Wall 
DEBUG = no
CC= g++

.PHONY: all clean debug-memory debuging

all: $(EXEC)

$(EXEC): main.o Header.o
	$(CC) -o $@ $^ -L/usr/lib -lsqlite3

main.o: main.cpp Settings.h
	$(CC) $(CXXFLAGS) -o $@ -c $< 

Header.o: Header.cpp Header.h
	$(CC) $(CXXFLAGS) -o $@ -c $<

#Network.o: Network.cpp Network.h Host.h Algorithm.h DataBase.h Compare.h LinuxNotification.h
#	$(CC) $(CXXFLAGS) -o $@ -c $<

#LinuxNotification.o: LinuxNotification.cpp LinuxNotification.h Host.h
#	$(CC) $(CXXFLAGS) -o $@ -c $<

# Instruction to clean file generated by compilation
# 	as well as text files used
clean:
	rm *.o && rm $(EXEC)

# Instruction to clean the log file containing error message
cleanLog:
	rm logFile.txt
	
# Instruction to check for memory leaks with valgrind
debug-memory: $(EXEC)
	valgrind --leak-check=full -v --show-leak-kinds=all\
	 --track-origins=yes ./$(EXEC)

# Instruction to compile and run at the same time
run: $(EXEC)
	./$(EXEC)
